---
- name: Check file existence and attributes
  hosts: all
  gather_facts: false
  become: false

  vars:
    # Override with 'ansible-playbook -e target_path=<path>'
    target_path: "/etc/hosts"

  tasks:

    - name: Stat target path
      ansible.builtin.stat:
        path: "{{ target_path }}"
        follow: false
      register: stat_result
      changed_when: false
      check_mode: false

    - name: Show stat summary
      ansible.builtin.debug:
        msg:
          path: "{{ target_path }}"
          exists: "{{ stat_result.stat.exists | default(false) }}"
          is_directory: "{{ stat_result.stat.isdir | default(false) }}"
          is_file: "{{ stat_result.stat.isreg | default(false) }}"
          size_bytes: "{{ stat_result.stat.size | default(0) }}"
          mode: "{{ stat_result.stat.mode | default('') }}"
          owner: "{{ stat_result.stat.pw_name | default('') }}"
          group: "{{ stat_result.stat.gr_name | default('') }}"

    - name: Report when target does not exist
      ansible.builtin.debug:
        msg: "Target does not exist: {{ target_path }}"
      when: not stat_result.stat.exists | default(false)

    - name: Report when target is a directory
      ansible.builtin.debug:
        msg: "Target is a directory: {{ target_path }}"
      when: stat_result.stat.isdir | default(false)

    - name: Report when target is a regular file
      ansible.builtin.debug:
        msg: "Target is a regular file: {{ target_path }}"
      when: stat_result.stat.isreg | default(false)

