---
- name: Modify sshd Configuration
  hosts: all
  become: true
  gather_facts: false

  tasks:
 
    - name: PasswordAuthentication yes
      ansible.builtin.lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication yes"
        validate: 'sshd -t -f %s'
      notify: Restart sshd
      
  handlers:

    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

