---
- name: Modify sshd Configuration
  hosts: all
  become: true
  gather_facts: false
  vars_prompt:
    - name: yesorno
      prompt: PasswordAuthentication yes or no?
      private: false

  tasks:
 
    - name: PasswordAuthentication yes
      ansible.builtin.lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication {{ yesorno }}"
        validate: 'sshd -t -f %s'
      notify: Restart sshd
      
  handlers:

    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

