---
- name: Create example.txt file
  hosts: all
  become: true
  gather_facts: false
  vars:
    motdfile: "/etc/motd"

  tasks:

  - name: Create a text file
    ansible.builtin.copy:
      dest: "{{ motdfile }}"
      content: |
        Greetings on this Managed Host!
        Weather is nice today.
        Automation with Ansible is fun!

