---
- name: Ensure FTP Client Configuration
  hosts: ftpclients
  become: true
  gather_facts: false

  tasks:

  - name: latest version of lftp is installed
    ansible.builtin.dnf:
      name: lftp
      state: latest

