---
- name: Install and run apache or nginx with webcontent template
  hosts: all
  gather_facts: no
  become: yes
  tasks:

    - name: Testing input parameter webserver
      ansible.builtin.debug:
        var: webserver

    - name: Stop webservers on port 80
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
      loop:
        - httpd
        - nginx
      ignore_errors: true

    - name: Install webserver httpd or nginx
      ansible.builtin.package:
        name: "{{ webserver }}"
        state: latest

    - name: Start apache or nginx in foreground
      ansible.builtin.service:
        name: "{{ webserver }}"
        state: started
        enabled: true

    - name: Set location for webcontent
      ansible.builtin.set_fact:
        weblocation: "/var/www/html/"
      when: webserver == "httpd"
    - ansible.builtin.set_fact:
        weblocation: "/usr/share/nginx/html/"
      when: webserver == "nginx"

    - name: Create webcontent
      ansible.builtin.template:
        src: index.html.j2
        dest: "{{ weblocation }}index.html"
        owner: root
        group: root
        mode: '0644'

    - name: Bind eth0 to public zone
      ansible.posix.firewalld:
        zone: public
        interface: eth0
        permanent: true
        state: enabled

    - name: Open HTTP service in public zone
      ansible.posix.firewalld:
        zone: public
        service: http
        permanent: true
        state: enabled

    - name: Reload firewalld to apply changes
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: Check webcontent 200 status code from container
      ansible.builtin.uri:
        url: http://localhost
        return_content: true
      register: container_response

    - name: Debug container response
      ansible.builtin.debug:
        var: container_response.content

    - name: Check webcontent 200 status code from localhost
      ansible.builtin.uri:
        url: http://{{ ansible_host }}
        return_content: true
      register: localhost_response

    - name: Debug localhost response
      ansible.builtin.debug:
        var: localhost_response.content

