---
- name: Check if sshd service is running
  hosts: all
  gather_facts: no

  tasks:
 
    - name: Check if sshd service is running
      ansible.builtin.systemd:
        name: sshd
        state: started
      register: sshd_status
      check_mode: true

    - name: Display sshd service status
      ansible.builtin.debug:
        msg: |
          SSH daemon (sshd) service status:
          - Service is running: {{ sshd_status.status.ActiveState == 'active' }}
          - Service state: {{ sshd_status.status.ActiveState }}
          - Service enabled: {{ sshd_status.status.UnitFileState == 'enabled' }}
          - Service loaded: {{ sshd_status.status.LoadState == 'loaded' }}

