---
- name: Set up pip and passlib
  hosts: all
  gather_facts: false
  become: true

  tasks:

    - name: Install pip with dnf
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
          - python3-setuptools
          - python3-packaging
        state: present
      delegate_to: localhost
      run_once: true

    - name: Install passlib with pip
      ansible.builtin.pip:
        name: passlib
        state: present
      delegate_to: localhost
      run_once: true

    - name: Install cracklib/pwquality
      ansible.builtin.dnf:
        name:
          - libpwquality
          - cracklib-dicts
        state: present

