---
- name: Create three local users on all servers
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - "passwords.yml"

  vars:
    users_to_create:

      - name: "alice"
        pwd: "{{ pwd_alice }}"
        comment: "Alice User"
        shell: "/bin/bash"
        home: "/home/alice"

      - name: "bob"
        pwd: "{{ pwd_bob }}"
        comment: "Bob User"
        shell: "/bin/bash"
        home: "/home/bob"

      - name: "charlie"
        pwd: "{{ pwd_charlie }}"
        comment: "Charlie User"
        shell: "/bin/bash"
        home: "/home/charlie"

  tasks:

    - name: Install pip with dnf
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
          - python3-setuptools
          - python3-packaging
        state: present
      delegate_to: localhost
      run_once: true

    - name: Install passlib with pip
      ansible.builtin.pip:
        name: passlib
        state: present
      delegate_to: localhost
      run_once: true

    - name: Create local users
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.pwd | password_hash('sha512') }}"
        comment: "{{ item.comment }}"
        shell: "{{ item.shell }}"
        home: "{{ item.home }}"
        create_home: true
        state: present
      loop: "{{ users_to_create }}"

    - name: Force password change
      ansible.builtin.shell:
        cmd: "chage -d 0 {{ item.name }}"
      loop: "{{ users_to_create }}"

