---
- name: FTP server is installed
  hosts:
    - ftpservers
  become: true
  gather_facts: false
  vars_files:
    - vars/defaults-template.yml
    - vars/vars.yml

  tasks:

    - name: Packages are installed
      ansible.builtin.dnf:
        name: "{{ vsftpd_package }}"
        state: present

    - name: Ensure service is started
      ansible.builtin.service:
        name: "{{ vsftpd_service }}"
        state: started
        enabled: true

    - name: Configuration file is installed
      ansible.builtin.template:
        src: templates/vsftpd.conf.j2
        dest: "{{ vsftpd_config_file }}"
        owner: root
        group: root
        mode: 0600
        setype: etc_t
      notify: restart vsftpd

    - name: firewalld is installed
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: firewalld is started and enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: FTP port is open
      ansible.posix.firewalld:
        service: ftp
        permanent: true
        state: enabled
        immediate: true
 
    - name: FTP passive data ports are open
      ansible.posix.firewalld:
        port: 21000-21020/tcp
        permanent: true
        state: enabled
        immediate: true

  handlers:
    - name: restart vsftpd
      ansible.builtin.service:
        name: "{{ vsftpd_service }}"
        state: restarted


