---
- name: Backup
  hosts: all
  become: true
  gather_facts: false
  vars:
    source_dir: /var/www
    dest_dir: /tmp/www-backup

  tasks:

    - name: Install rsync
      ansible.builtin.dnf:
        name: rsync
        state: present

    - name: Backup files with rsync
      ansible.posix.synchronize:
        src: "{{ source_dir }}"
        dest: "{{ dest_dir }}"
        mode: pull
      become: false
      delegate_to: host1
      run_once: true

