---
- name: Backup
  hosts: all
  become: true
  gather_facts: yes
  vars:
    source_dir: /var/www
    dest_dir: /tmp/www-backup

  tasks:

    - name: Install rsync
      ansible.builtin.dnf:
        name: rsync
        state: present

    - name: Print all hosts
      ansible.builtin.debug:
        var: ansible_play_hosts_all

    - name: Backup files with rsync
      ansible.posix.synchronize:
        src: "{{ source_dir }}"
        dest: "{{ dest_dir }}/{{ item }}"
        mode: pull
      loop: ansible_play_hosts_all
      become: false
      delegate_to: localhost
      run_once: true

