---
- name: Install rsync
  hosts: all
  become: true
  gather_facts: false
  vars:
    source_path: /var/www
    dest_path: /tmp/backup/rsync

  tasks:

    - name: Install rsync
      ansible.builtin.dnf:
        name: rsync
        state: present

    - name: Print all hosts
      ansible.builtin.debug:
        var: ansible_play_hosts_all
      run_once: true

    - name: Create host dir under dest_dir
      ansible.builtin.file:
        path: "{{ dest_path }}"
        state: directory
        owner: devops
        group: devops
        mode: '0755'

    - name: Backup files with rsync
      ansible.posix.synchronize:
        src: "{{ source_path }}"
        dest: "{{ dest_path }}/{{ ansible_host }}"
        mode: pull
      when: inventory_hostname != 'localhost'
      become: false

