FROM registry.fedoraproject.org/fedora:latest

# Doesn't install ansible, first excersice will

RUN dnf install -y \
    openssh-clients \
    sshd \
    sudo \
    iproute \
    openssh-server \
    passwd \
    ip \
    ps \
    tree \
    vim \
    ping \
    sshpass \
    podman \
    python3 \
    python3-dnf && \
    systemd \
    systemd-libs \
    systemd-container \
    procps-ng \
    firewalld \
  dnf clean all && \
  echo "root:root" | chpasswd && \
  ssh-keygen -A

COPY ssh_config /etc/ssh/

# Enable root ssh login and password login
COPY sshd_config /etc/ssh/

# Enable sshd service
RUN mkdir -p /var/run/sshd && \
    systemctl enable sshd.service

# Expose ssh port
EXPOSE 22

# Systemd needs a few things mounted when container runs
VOLUME [ "/sys/fs/cgroup" ]

# Use systemd as PID 1
CMD ["/usr/sbin/init"]

