FROM fedora:latest

# Doesn't install ansible, first excersice will

RUN dnf install -y \
    openssh-clients \
    sshd \
    sudo \
    iproute \
    openssh-server \
    passwd \
    ip \
    tree \
    vim \
    ping \
    sshpass \
    podman \
    python3 \
    python3-dnf && \
    dnf clean all && \
    echo "root:root" | chpasswd && \
    ssh-keygen -A

COPY ssh_config /etc/ssh/

# Enable root ssh login and password login
COPY sshd_config /etc/ssh/

# Enable sshd service
RUN mkdir -p /var/run/sshd && \
    systemctl enable sshd.service

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]

