---
- name: Hostdata gather
  hosts: all
  gather_facts: true

  tasks:

    - name: Hostdata template
      ansible.builtin.template:
        src: hostdata.j2
        dest: /tmp/hostdata

    - name: Debug hostdata file content
      ansible.builtin.command:
        cmd: cat /tmp/hostdata
      register: result_command
    - ansible.builtin.debug:
        msg: "{{ result_command.stdout }}"
      run_once: true

