- name: Check Multiple Services State
  hosts: all
  become: false
  gather_facts: false

  tasks:

    - name: Check services is-active
      ansible.builtin.shell: systemctl is-active {{ item }}
      register: results_state
      loop:
        - sshd
        - nginx
        - firewalld
      ignore_errors: true

    - name: Format and print result
      block:
        - ansible.builtin.set_fact:
            str: "{{ item.item }} state: {{ item.stdout }}"
        - ansible.builtin.debug:
            var: "{{ str }}"
      loop: "{{ results_state.results }}"

