- name: Check Multiple Services State
  hosts: all
  become: false
  gather_facts: false

  tasks:

    - name: Check services is-active
      ansible.builtin.shell: systemctl is-active {{ item }}
      register: results_state
      loop:
        - sshd
        - nginx
        - firewalld
      ignore_errors: true

    - name: Display Full Results
      ansible.builtin.debug:
        var: results_state

    - name: Display Services State
      ansible.builtin.debug:
        var: "{{ item.cmd }}"
      loop: "{{ results_state.results }}"
      
