- name: Check Multiple Services State
  hosts: all
  become: false
  gather_facts: false

  tasks:

    - name: Check services is-active
      shell: systemctl is-active {{ item }}
      register: results_state
      loop:
        - sshd
        - nginx
        - firewalld
      ignore_errors: true

    - name: Display Services State
      debug:
        msg: |
          {{ item.item }} 
          {{ item.stdout }}

      loop: "{{ results_state.results }}"
      
